spring:
  profiles:
    active: default

  datasource:
    url: jdbc:postgresql://localhost:5432/soutside4u_product
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    